# LSTM Cheatsheet

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Load the Airline Passengers dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"
df = pd.read_csv(url)

# Prepare the data
data = df['Passengers'].values.astype('float32')

In [32]:
data

array([112., 118., 132., 129., 121., 135., 148., 148., 136., 119., 104.,
       118., 115., 126., 141., 135., 125., 149., 170., 170., 158., 133.,
       114., 140., 145., 150., 178., 163., 172., 178., 199., 199., 184.,
       162., 146., 166., 171., 180., 193., 181., 183., 218., 230., 242.,
       209., 191., 172., 194., 196., 196., 236., 235., 229., 243., 264.,
       272., 237., 211., 180., 201., 204., 188., 235., 227., 234., 264.,
       302., 293., 259., 229., 203., 229., 242., 233., 267., 269., 270.,
       315., 364., 347., 312., 274., 237., 278., 284., 277., 317., 313.,
       318., 374., 413., 405., 355., 306., 271., 306., 315., 301., 356.,
       348., 355., 422., 465., 467., 404., 347., 305., 336., 340., 318.,
       362., 348., 363., 435., 491., 505., 404., 359., 310., 337., 360.,
       342., 406., 396., 420., 472., 548., 559., 463., 407., 362., 405.,
       417., 391., 419., 461., 472., 535., 622., 606., 508., 461., 390.,
       432.], dtype=float32)

In [33]:
# Normalize the data
scaler = MinMaxScaler(feature_range=(0, 1))
data = scaler.fit_transform(data.reshape(-1, 1))

In [34]:
data

array([[0.01544401],
       [0.02702703],
       [0.05405405],
       [0.04826255],
       [0.03281853],
       [0.05984557],
       [0.08494207],
       [0.08494207],
       [0.06177607],
       [0.02895753],
       [0.        ],
       [0.02702703],
       [0.02123553],
       [0.04247104],
       [0.07142857],
       [0.05984557],
       [0.04054055],
       [0.08687258],
       [0.12741312],
       [0.12741312],
       [0.10424709],
       [0.05598456],
       [0.01930502],
       [0.06949806],
       [0.07915059],
       [0.08880308],
       [0.14285713],
       [0.11389962],
       [0.13127413],
       [0.14285713],
       [0.18339768],
       [0.18339768],
       [0.15444016],
       [0.11196911],
       [0.08108109],
       [0.1196911 ],
       [0.12934363],
       [0.14671814],
       [0.17181468],
       [0.14864865],
       [0.15250966],
       [0.22007722],
       [0.24324325],
       [0.26640925],
       [0.2027027 ],
       [0.16795367],
       [0.13127413],
       [0.173

In [35]:
data

array([[0.01544401],
       [0.02702703],
       [0.05405405],
       [0.04826255],
       [0.03281853],
       [0.05984557],
       [0.08494207],
       [0.08494207],
       [0.06177607],
       [0.02895753],
       [0.        ],
       [0.02702703],
       [0.02123553],
       [0.04247104],
       [0.07142857],
       [0.05984557],
       [0.04054055],
       [0.08687258],
       [0.12741312],
       [0.12741312],
       [0.10424709],
       [0.05598456],
       [0.01930502],
       [0.06949806],
       [0.07915059],
       [0.08880308],
       [0.14285713],
       [0.11389962],
       [0.13127413],
       [0.14285713],
       [0.18339768],
       [0.18339768],
       [0.15444016],
       [0.11196911],
       [0.08108109],
       [0.1196911 ],
       [0.12934363],
       [0.14671814],
       [0.17181468],
       [0.14864865],
       [0.15250966],
       [0.22007722],
       [0.24324325],
       [0.26640925],
       [0.2027027 ],
       [0.16795367],
       [0.13127413],
       [0.173

In [22]:
# Modified create_sequences function
def create_sequences(data, input_steps, output_steps):
    """
    Create sequences for time series prediction

    Parameters:
    data: input time series data
    input_steps: number of time steps in the input sequence
    output_steps: number of time steps in the output sequence
    """
    X, y = [], []
    for i in range(len(data) - input_steps - output_steps + 1):
        # Input sequence (features)
        X.append(data[i:(i + input_steps), 0])
        # Output sequence (targets)
        y.append(data[(i + input_steps):(i + input_steps + output_steps), 0])
    return np.array(X), np.array(y)

In [52]:
# Create sequences: 12 months input -> 3 months output
input_steps = 12
output_steps = 7
X, y = create_sequences(data, input_steps, output_steps)

In [54]:
y

array([[0.02123553, 0.04247104, 0.07142857, 0.05984557, 0.04054055,
        0.08687258, 0.12741312],
       [0.04247104, 0.07142857, 0.05984557, 0.04054055, 0.08687258,
        0.12741312, 0.12741312],
       [0.07142857, 0.05984557, 0.04054055, 0.08687258, 0.12741312,
        0.12741312, 0.10424709],
       [0.05984557, 0.04054055, 0.08687258, 0.12741312, 0.12741312,
        0.10424709, 0.05598456],
       [0.04054055, 0.08687258, 0.12741312, 0.12741312, 0.10424709,
        0.05598456, 0.01930502],
       [0.08687258, 0.12741312, 0.12741312, 0.10424709, 0.05598456,
        0.01930502, 0.06949806],
       [0.12741312, 0.12741312, 0.10424709, 0.05598456, 0.01930502,
        0.06949806, 0.07915059],
       [0.12741312, 0.10424709, 0.05598456, 0.01930502, 0.06949806,
        0.07915059, 0.08880308],
       [0.10424709, 0.05598456, 0.01930502, 0.06949806, 0.07915059,
        0.08880308, 0.14285713],
       [0.05598456, 0.01930502, 0.06949806, 0.07915059, 0.08880308,
        0.14285713, 0.1

In [56]:
X = X.reshape((X.shape[0], X.shape[1], 1))

In [66]:
# SUPER SIMPLE MODEL -
model = Sequential([
    LSTM(5, input_shape=(input_steps, 1)),  # LSTM layer

    Dense(output_steps)                       # Single output layer
])

model.compile(optimizer='adam', loss='mse')
model.summary()

# Train
model.fit(X, y)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_5 (LSTM)                   │ (None, 5)              │           140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 146 (584.00 B)

 Trainable params: 146 (584.00 B)

 Non-trainable params: 0 (0.00 B)

4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.2101


In [61]:
model.predict(data[-input_steps:].reshape(1, input_steps, 1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step


array([[ 0.01351895, -0.5006568 ,  0.39782175,  0.09832503,  0.11326627,
         0.23382251, -0.1901789 ]], dtype=float32)

In [62]:

# Make prediction
last_sequence = data[-input_steps:].reshape(1, input_steps, 1)
prediction = model.predict(last_sequence)

print(f"Next {output_steps} days predictions: {prediction[0]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Next 7 days predictions: [ 0.01351895 -0.5006568   0.39782175  0.09832503  0.11326627  0.23382251
 -0.1901789 ]


In [63]:
prediction

array([[ 0.01351895, -0.5006568 ,  0.39782175,  0.09832503,  0.11326627,
         0.23382251, -0.1901789 ]], dtype=float32)

In [64]:
scaler.inverse_transform(prediction)

array([[ 111.002815, -155.34023 ,  310.0717  ,  154.93237 ,  162.67192 ,
         225.12006 ,    5.487327]], dtype=float32)

## Iterative future predictor

In [65]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Assuming you already have:
# - trained model
# - scaler (if you scaled the data)
# - input_steps = 12
# - data (your original or scaled data)

def predict_future(model, last_sequence, n_future):
    """
    Predict future values iteratively

    Parameters:
    model: trained LSTM model
    last_sequence: last known sequence of data (length = input_steps)
    n_future: how many future steps to predict
    """
    future_predictions = []
    current_sequence = last_sequence.copy()

    for i in range(n_future):
        # Make prediction for next step
        next_pred = model.predict(current_sequence.reshape(1, input_steps, 1), verbose=0)
        future_predictions.append(next_pred[0, 0])

        # Update the sequence: remove first element, add new prediction
        current_sequence = np.roll(current_sequence, -1)
        current_sequence[-1] = next_pred[0, 0]

    return np.array(future_predictions)

# Example usage:
input_steps = 12
n_future = 6  # Predict next 6 time steps

# Get last known sequence from your data
last_sequence = data[-input_steps:]  # Last 12 known values

# Get future predictions
future_predictions = predict_future(model, last_sequence, n_future)

print(f"Next {n_future} predictions: {future_predictions}")

Next 6 predictions: [0.01351895 0.01443397 0.01608272 0.01703871 0.01722324 0.01674399]
